openapi: 3.2.0
info:
  title: OpenAgri Farm Calendar Crop Stress Indicator Observations…
  version: 1.0.0
  description: API for farm assets and other farm related things.
tags:
- name: CropStressIndicatorObservations
paths:
  /api/v1/CropStressIndicatorObservations/:
    get:
      operationId: api_v1_CropStressIndicatorObservations_list
      description: API endpoint that allows CropStressIndicator to be viewed or edited.
      parameters:
      - in: query
        name: activity_type
        schema:
          type: string
          format: uuid
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: query
        name: fromDate
        schema:
          type: string
          format: date-time
      - in: query
        name: parcel
        schema:
          type: string
          format: uuid
      - in: query
        name: responsible_agent
        schema:
          type: string
      - in: query
        name: title
        schema:
          type: string
      - in: query
        name: toDate
        schema:
          type: string
          format: date-time
      tags:
      - CropStressIndicatorObservations
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CropStressIndicatorObservation'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CropStressIndicatorObservation'
          description: ''
      summary: Api v1 crop stress indicator observations list
      x-summary-source: derived
    post:
      operationId: api_v1_CropStressIndicatorObservations_create
      description: API endpoint that allows CropStressIndicator to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      tags:
      - CropStressIndicatorObservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CropStressIndicatorObservation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CropStressIndicatorObservation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CropStressIndicatorObservation'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
            application/json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
          description: ''
      summary: Api v1 crop stress indicator observations create
      x-summary-source: derived
  /api/v1/CropStressIndicatorObservations/{id}/:
    get:
      operationId: api_v1_CropStressIndicatorObservations_retrieve
      description: API endpoint that allows CropStressIndicator to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Crop Stress Indicator Observation.
        required: true
      tags:
      - CropStressIndicatorObservations
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
            application/json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
          description: ''
      summary: Api v1 crop stress indicator observations retrieve
      x-summary-source: derived
    put:
      operationId: api_v1_CropStressIndicatorObservations_update
      description: API endpoint that allows CropStressIndicator to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Crop Stress Indicator Observation.
        required: true
      tags:
      - CropStressIndicatorObservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CropStressIndicatorObservation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CropStressIndicatorObservation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CropStressIndicatorObservation'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
            application/json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
          description: ''
      summary: Api v1 crop stress indicator observations update
      x-summary-source: derived
    patch:
      operationId: api_v1_CropStressIndicatorObservations_partial_update
      description: API endpoint that allows CropStressIndicator to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Crop Stress Indicator Observation.
        required: true
      tags:
      - CropStressIndicatorObservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCropStressIndicatorObservation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCropStressIndicatorObservation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCropStressIndicatorObservation'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
            application/json:
              schema:
                $ref: '#/components/schemas/CropStressIndicatorObservation'
          description: ''
      summary: Api v1 crop stress indicator observations partial update
      x-summary-source: derived
    delete:
      operationId: api_v1_CropStressIndicatorObservations_destroy
      description: API endpoint that allows CropStressIndicator to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Crop Stress Indicator Observation.
        required: true
      tags:
      - CropStressIndicatorObservations
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
      summary: Api v1 crop stress indicator observations destroy
      x-summary-source: derived
components:
  schemas:
    CropStressIndicatorObservation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        activityType:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        details:
          type:
          - string
          - 'null'
        phenomenonTime:
          type: string
          format: date-time
        hasEndDatetime:
          type:
          - string
          - 'null'
          format: date-time
        madeBySensor:
          allOf:
          - $ref: '#/components/schemas/MadeBySensorField'
        hasAgriParcel:
          type: string
          format: uuid
        hasAgriCrop:
          type: string
          format: uuid
        hasResult:
          $ref: '#/components/schemas/GenericQuantityValueField'
        observedProperty:
          type: string
      required:
      - activityType
      - hasAgriCrop
      - hasAgriParcel
      - hasResult
      - id
      - observedProperty
      - phenomenonTime
    PatchedCropStressIndicatorObservation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        activityType:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        details:
          type:
          - string
          - 'null'
        phenomenonTime:
          type: string
          format: date-time
        hasEndDatetime:
          type:
          - string
          - 'null'
          format: date-time
        madeBySensor:
          allOf:
          - $ref: '#/components/schemas/MadeBySensorField'
        hasAgriParcel:
          type: string
          format: uuid
        hasAgriCrop:
          type: string
          format: uuid
        hasResult:
          $ref: '#/components/schemas/GenericQuantityValueField'
        observedProperty:
          type: string
    MadeBySensorField:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
      required:
      - name
    GenericQuantityValueField:
      type: object
      properties:
        unit:
          type:
          - string
          - 'null'
        hasValue:
          type: string
      required:
      - hasValue
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
