openapi: 3.2.0
info:
  title: OpenAgri Farm Calendar Fertilization Operations API
  version: 1.0.0
  description: API for farm assets and other farm related things.
tags:
- name: FertilizationOperations
paths:
  /api/v1/FertilizationOperations/:
    get:
      operationId: api_v1_FertilizationOperations_list
      description: API endpoint that allows FertilizationOperation to be viewed or edited.
      parameters:
      - in: query
        name: activity_type
        schema:
          type: string
          format: uuid
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: query
        name: fromDate
        schema:
          type: string
          format: date-time
      - in: query
        name: parcel
        schema:
          type: string
          format: uuid
      - in: query
        name: responsible_agent
        schema:
          type: string
      - in: query
        name: title
        schema:
          type: string
      - in: query
        name: toDate
        schema:
          type: string
          format: date-time
      tags:
      - FertilizationOperations
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FertilizationOperation'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FertilizationOperation'
          description: ''
      summary: Api v1 fertilization operations list
      x-summary-source: derived
    post:
      operationId: api_v1_FertilizationOperations_create
      description: API endpoint that allows FertilizationOperation to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      tags:
      - FertilizationOperations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FertilizationOperation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FertilizationOperation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FertilizationOperation'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
            application/json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
          description: ''
      summary: Api v1 fertilization operations create
      x-summary-source: derived
  /api/v1/FertilizationOperations/{id}/:
    get:
      operationId: api_v1_FertilizationOperations_retrieve
      description: API endpoint that allows FertilizationOperation to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Fertilization Operation.
        required: true
      tags:
      - FertilizationOperations
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
            application/json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
          description: ''
      summary: Api v1 fertilization operations retrieve
      x-summary-source: derived
    put:
      operationId: api_v1_FertilizationOperations_update
      description: API endpoint that allows FertilizationOperation to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Fertilization Operation.
        required: true
      tags:
      - FertilizationOperations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FertilizationOperation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FertilizationOperation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FertilizationOperation'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
            application/json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
          description: ''
      summary: Api v1 fertilization operations update
      x-summary-source: derived
    patch:
      operationId: api_v1_FertilizationOperations_partial_update
      description: API endpoint that allows FertilizationOperation to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Fertilization Operation.
        required: true
      tags:
      - FertilizationOperations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedFertilizationOperation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedFertilizationOperation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedFertilizationOperation'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
            application/json:
              schema:
                $ref: '#/components/schemas/FertilizationOperation'
          description: ''
      summary: Api v1 fertilization operations partial update
      x-summary-source: derived
    delete:
      operationId: api_v1_FertilizationOperations_destroy
      description: API endpoint that allows FertilizationOperation to be viewed or edited.
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - jsonld
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Fertilization Operation.
        required: true
      tags:
      - FertilizationOperations
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
      summary: Api v1 fertilization operations destroy
      x-summary-source: derived
components:
  schemas:
    AppliedAmmountField:
      type: object
      properties:
        unit:
          type: string
        numericValue:
          type: string
          format: decimal
          pattern: ^-?\d{0,15}(?:\.\d{0,2})?$
      required:
      - numericValue
      - unit
    PatchedFertilizationOperation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        activityType:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        details:
          type:
          - string
          - 'null'
        hasStartDatetime:
          type: string
          format: date-time
        hasEndDatetime:
          type:
          - string
          - 'null'
          format: date-time
        responsibleAgent:
          type:
          - string
          - 'null'
        usesAgriculturalMachinery:
          type: array
          items:
            type: string
            format: uuid
        hasAppliedAmount:
          $ref: '#/components/schemas/AppliedAmmountField'
        hasApplicationMethod:
          type:
          - string
          - 'null'
        usesFertilizer:
          type:
          - string
          - 'null'
          format: uuid
        operatedOn:
          type: string
          format: uuid
    FertilizationOperation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        activityType:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        details:
          type:
          - string
          - 'null'
        hasStartDatetime:
          type: string
          format: date-time
        hasEndDatetime:
          type:
          - string
          - 'null'
          format: date-time
        responsibleAgent:
          type:
          - string
          - 'null'
        usesAgriculturalMachinery:
          type: array
          items:
            type: string
            format: uuid
        hasAppliedAmount:
          $ref: '#/components/schemas/AppliedAmmountField'
        hasApplicationMethod:
          type:
          - string
          - 'null'
        usesFertilizer:
          type:
          - string
          - 'null'
          format: uuid
        operatedOn:
          type: string
          format: uuid
      required:
      - activityType
      - hasApplicationMethod
      - hasAppliedAmount
      - hasStartDatetime
      - id
      - operatedOn
      - usesAgriculturalMachinery
      - usesFertilizer
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
